### ISSUE TITLE
Service accounts only, no support for user accounts? "AttributeError: 'Credentials' object has no attribute 'service_account_email'"

### ISSUE THREAD

**Issue by jim-mccabe** [googleapis/managedkafka#20]
### Background context

I'm trying to migrate services from a self-hosted Kafka cluster to a Google-hosted cluster.  We are trying to use this `managedkafka` proxy to manage the OAuth tokens.

An important requirement for us is that developers need to be able to publish & consume messages when running a service locally.  For example if I am adding a new feature to a service, I need to be able to test it locally, pointing to a Kafka cluster in our QA environment.

### The issue

I have a testbed which lets me experiment with this migration, publishing 10 messages and then consuming them back.  It works great with our self-hosted cluster, but when I configure it to use this proxy (with [the settings in the README](https://github.com/googleapis/managedkafka?tab=readme-ov-file#local-auth-server)) it fails to authenticate.

My environment is:

* OS: MacOS Sonoma 14.5
* JDK: Amazon Corretto 8.0.412
* Apache `kafka-clients` version 3.4.1

I see errors in the auth proxy logs and exceptions in the JVM testbed.  In my Java service I see this:

```
16:41:32.103 [main] WARN  o.a.k.c.s.o.internals.secured.Retry - Error during retry attempt 1
java.util.concurrent.ExecutionException: java.io.IOException: The token endpoint response was unexpectedly empty despite response code 200 from http://localhost:14293 and error message {}
	at org.apache.kafka.common.security.oauthbearer.internals.secured.HttpAccessTokenRetriever.lambda$retrieve$0(HttpAccessTokenRetriever.java:171)
	at org.apache.kafka.common.security.oauthbearer.internals.secured.Retry.execute(Retry.java:70)
	at org.apache.kafka.common.security.oauthbearer.internals.secured.HttpAccessTokenRetriever.retrieve(HttpAccessTokenRetriever.java:160)
	at org.apache.kafka.common.security.oauthbearer.OAuthBearerLoginCallbackHandler.handleTokenCallback(OAuthBearerLoginCallbackHandler.java:244)
	at org.apache.kafka.common.security.oauthbearer.OAuthBearerLoginCallbackHandler.handle(OAuthBearerLoginCallbackHandler.java:233)
	at org.apache.kafka.common.security.oauthbearer.OAuthBearerLoginModule.identifyToken(OAuthBearerLoginModule.java:316)
	at org.apache.kafka.common.security.oauthbearer.OAuthBearerLoginModule.login(OAuthBearerLoginModule.java:301)
(dozens of lines edited out by me)
Caused by: java.io.IOException: The token endpoint response was unexpectedly empty despite response code 200 from http://localhost:14293 and error message {}
	at org.apache.kafka.common.security.oauthbearer.internals.secured.HttpAccessTokenRetriever.handleOutput(HttpAccessTokenRetriever.java:275)
	at org.apache.kafka.common.security.oauthbearer.internals.secured.HttpAccessTokenRetriever.post(HttpAccessTokenRetriever.java:194)
	at org.apache.kafka.common.security.oauthbearer.internals.secured.HttpAccessTokenRetriever.lambda$retrieve$0(HttpAccessTokenRetriever.java:169)
	... 38 common frames omitted
```

In the auth proxy console I see this:

```
Exception occurred during processing of request from ('127.0.0.1', 53661)
Traceback (most recent call last):
  File "/opt/homebrew/Cellar/python@3.12/3.12.4/Frameworks/Python.framework/Versions/3.12/lib/python3.12/socketserver.py", line 692, in process_request_thread
    self.finish_request(request, client_address)
  File "/opt/homebrew/Cellar/python@3.12/3.12.4/Frameworks/Python.framework/Versions/3.12/lib/python3.12/socketserver.py", line 362, in finish_request
    self.RequestHandlerClass(request, client_address, self)
  File "/opt/homebrew/Cellar/python@3.12/3.12.4/Frameworks/Python.framework/Versions/3.12/lib/python3.12/socketserver.py", line 761, in __init__
    self.handle()
  File "/opt/homebrew/Cellar/python@3.12/3.12.4/Frameworks/Python.framework/Versions/3.12/lib/python3.12/http/server.py", line 436, in handle
    self.handle_one_request()
  File "/opt/homebrew/Cellar/python@3.12/3.12.4/Frameworks/Python.framework/Versions/3.12/lib/python3.12/http/server.py", line 424, in handle_one_request
    method()
  File "/Users/jimmccabe/bin/gcloud/managedkafka/kafka-auth-local-server/kafka_gcp_credentials_server.py", line 98, in do_POST
    self._handle()
  File "/Users/jimmccabe/bin/gcloud/managedkafka/kafka-auth-local-server/kafka_gcp_credentials_server.py", line 89, in _handle
    message = build_message().encode('utf-8')
              ^^^^^^^^^^^^^^^
  File "/Users/jimmccabe/bin/gcloud/managedkafka/kafka-auth-local-server/kafka_gcp_credentials_server.py", line 75, in build_message
    access_token=get_kafka_access_token(creds),
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/jimmccabe/bin/gcloud/managedkafka/kafka-auth-local-server/kafka_gcp_credentials_server.py", line 64, in get_kafka_access_token
    [b64_encode(_HEADER), b64_encode(get_jwt(creds)), b64_encode(creds.token)]
                                     ^^^^^^^^^^^^^^
  File "/Users/jimmccabe/bin/gcloud/managedkafka/kafka-auth-local-server/kafka_gcp_credentials_server.py", line 49, in get_jwt
    sub=creds.service_account_email,
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'Credentials' object has no attribute 'service_account_email'
----------------------------------------
127.0.0.1 - - [05/Sep/2024 16:41:32] "POST / HTTP/1.1" 200 -
```

I am authenticated with `gcloud` locally, but I have user credentials, not a service account.  Individual `gcloud` auth is sufficient with other Google libs that we use, for example Cloud Storage and Secrets.

* Does this proxy only work when running inside of a Kubernetes cluster?
* Does it only work with service accounts, and not with user credentials?

The README says this:

> In either case, your client leverages Google Auth libraries for authentication using default environment credentials. On GCP environments like GKE or GCE, this typically implies using the environment service accounts. You can override this behavior and specify different credentials using the GOOGLE_APPLICATION_CREDENTIALS environment variable, as detailed in [this article](https://github.com/googleapis/google-auth-library-java?tab=readme-ov-file#getting-application-default-credentials).

I don't have a `GOOGLE_APPLICATION_CREDENTIALS` environment variable, but I am definitely authenticated with `gcloud auth`.  For example, `gcloud auth list` shows my credentialed account, `gcloud auth application-default print-access-token` successfully prints out a token, etc.

**Comment by benjamin-maynard** [comment]
b/384897948

**Comment by acocuzzo** [comment]
> 1. Does this proxy only work when running inside of a Kubernetes cluster?

No, you can also run this inside a Compute Engine instance that can access the VPC containing the default subnet where the Kafka cluster is reachable:
https://cloud.google.com/managed-service-for-apache-kafka/docs/quickstart#set_up_a_client_machine

For more background on using the service account attached to the Compute Engine instance, see: https://cloud.google.com/docs/authentication/rest#rest-request

> 2. Does it only work with service accounts, and not with user credentials?
User credentials are not supported for system-to-system communication. You may want to try impersonated credentials: https://cloud.google.com/docs/authentication/use-service-account-impersonation

**Comment by acocuzzo** [comment]
Update: We're going to work on a solution for allowing user credentials, since using impersonated credentials is likely going to be too much user-friction, and user credentials should be fine for this type of use case.
